name : My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4

            - name: List and read file
              run: |
                echo "My First Github Actions Job"
                ls -ltra
                cat README.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run it" >> dragon.txt

            #- name: list files
             # run: ls 

            #- name: Read file
             # run: cat README.md
